Some small scripts to help updating python3 packages on the openSUSE
build server:

https://build.opensuse.org/project/show/devel:languages:python3

* Files

** dlp3-update.py

Check for updated version on pypi, print a list of packages that need
updates together with the a link where the changelog information can be found.
Also manage the json file that stores the changelog information

** dlp3-monitor.py

Check the build status of several packages at the same time. Automate
submission to dlp3 for package that build correctly. Also produce
cleanup commands for packages that got accepted and therefore are not
on OBS, but still on the local computer.

** package-changelog-data.json

The file that stores the links to the changelog files. If there is no
changelog available, but a git repository exist the command to clone
the git repo should be stored.

** dlp3-update.conf

A simple config file that stores the path information. You can also
define a list of packages that should be skipped during update checks.

* Installation

Adjust the config file, so that it has the correct path information.

Just use the files directly from the git-repo or create links into for
example your ~/bin directory. In this case you should also link the
config file to ~/.config/dlp3-update/


* TODO
  - The monitor program could check every 5 seconds automatically
  - Handle packages that don't build correctly better, e.g. also check
    for updates for packages in your home-branch, but only list them
    if there is a newer version available then the one you are already
    working on
  - open changelogs automatically in your browser
